use_frameworks! :linkage => :static

target 'TaxiApp' do

pod 'FirebaseFirestore'
pod 'FirebaseStorage'
pod 'GeoFire/Utils'

end

target 'Driver' do

pod 'FirebaseAuth'
pod 'FirebaseFirestore'
pod 'FirebaseStorage'
pod 'GeoFire/Utils'

end
